/* Shared demo catalogue; venue markers identify the area, not a show ring. */
window.CK_EVENT_CATALOG = [
  {
    id: 1,
    date: "2026-08-29",
    day: "29",
    month: "srpna",
    weekday: "sobota",
    type: "Národní",
    title: "Národní výstava psů Brno",
    city: "Brno",
    venue: "BVV — Výstaviště Brno",
    location: { lat: 49.1883556, lon: 16.5856278 },
    dogs: 842,
    capacity: 1200,
    deadline: "20. 8. 2026",
    organizer: "Moravskoslezský kynologický svaz",
    contact: "vystavy@kynologie-brno.cz",
    judges: "18 rozhodčích z 8 zemí",
    description:
      "Celostátní výstava všech plemen se zadáváním titulů CAJC, CAC ČR a Národní vítěz. Součástí programu budou také soutěže mladých vystavovatelů a chovatelských skupin.",
  },
  {
    id: 2,
    date: "2026-09-05",
    day: "05",
    month: "září",
    weekday: "sobota",
    type: "Mezinárodní",
    title: "Prague Expo Dog",
    city: "Praha",
    venue: "PVA EXPO Letňany",
    location: { lat: 50.1282394, lon: 14.5143553 },
    dogs: 1368,
    capacity: 1800,
    deadline: "25. 8. 2026",
    organizer: "Kynologická jednota České republiky",
    contact: "info@pragueexpodog.cz",
    judges: "26 rozhodčích z 12 zemí",
    description:
      "Mezinárodní výstava všech plemen FCI v moderním areálu PVA EXPO. Zadávají se tituly CACIB, CAJC, CAC ČR a BOB. Parkování a veterinární přejímka přímo v areálu.",
  },
  {
    id: 3,
    date: "2026-09-12",
    day: "12",
    month: "září",
    weekday: "sobota",
    type: "Klubová",
    title: "Klubová výstava retrívrů",
    city: "Konopiště",
    venue: "Zámecký park Konopiště",
    location: { lat: 49.7795518, lon: 14.6567153 },
    dogs: 214,
    capacity: 320,
    deadline: "2. 9. 2026",
    organizer: "Retriever klub CZ",
    contact: "vystava@retrieverklub.cz",
    judges: "4 specialisté na plemena retrívrů",
    description:
      "Klubová výstava retrívrů v přírodním prostředí zámeckého parku. Otevřeny jsou všechny standardní třídy, soutěž Nejlepší chovatelská skupina a Junior handling.",
  },
  {
    id: 4,
    date: "2026-09-19",
    day: "19",
    month: "září",
    weekday: "sobota",
    type: "Mezinárodní",
    title: "International Dog Show České Budějovice",
    city: "České Budějovice",
    venue: "Výstaviště České Budějovice",
    location: { lat: 48.9789236, lon: 14.46088 },
    dogs: 1106,
    capacity: 1600,
    deadline: "8. 9. 2026",
    organizer: "Jihočeský kynologický klub",
    contact: "office@ids-cb.cz",
    judges: "22 rozhodčích z 10 zemí",
    description:
      "Tradiční mezinárodní výstava v Českých Budějovicích pro všechna plemena FCI. Přihlášení probíhá online a vstupní list bude k dispozici v členské zóně.",
  },
  {
    id: 5,
    date: "2026-09-26",
    day: "26",
    month: "září",
    weekday: "sobota",
    type: "Národní",
    title: "Slezská národní výstava",
    city: "Ostrava",
    venue: "Černá louka — pavilon A",
    location: { lat: 49.8331111, lon: 18.2932947 },
    dogs: 673,
    capacity: 1050,
    deadline: "15. 9. 2026",
    organizer: "Kynologický klub Ostrava",
    contact: "vystava@kkostrava.cz",
    judges: "16 rozhodčích z 6 zemí",
    description:
      "Jednodenní národní výstava všech plemen s doprovodným programem pro rodiny a prezentací českých národních plemen. K dispozici bude veterinární poradna.",
  },
  {
    id: 6,
    date: "2026-10-10",
    day: "10",
    month: "října",
    weekday: "sobota",
    type: "Speciální",
    title: "Speciální výstava ovčáckých plemen",
    city: "Mladá Boleslav",
    venue: "Krásná louka",
    location: { lat: 50.4218611, lon: 14.899 },
    dogs: 186,
    capacity: 280,
    deadline: "28. 9. 2026",
    organizer: "Klub ovčáckých a pasteveckých plemen",
    contact: "specialka@kopp.cz",
    judges: "5 specialistů FCI skupiny I",
    description:
      "Speciální výstava plemen FCI skupiny I s možností získat titul Vítěz speciální výstavy. Součástí dne je komentovaná přehlídka pracovních vloh pasteveckých psů.",
  },
];
